module.exports = {
  ACCESS_TOKEN_EXPIRY: '15m',
  REFRESH_TOKEN_EXPIRY: '7d',
  REFRESH_TOKEN_EXPIRY_MS: 7 * 24 * 60 * 60 * 1000,
  BCRYPT_COST: 12,
  DEFAULT_BOOKING_WINDOW_DAYS: 60,
  ROUND_ROBIN_WINDOW_DAYS: 30,
  REMINDER_LEAD_MINUTES: 24 * 60
};
